### ISSUE TITLE
Cannot run on OSX

### ISSUE THREAD

**Issue by jbmouret** [bibcure/bibcure#13]
Hello

I installed bibcure with pip (I tried with both pip and pip3). Everything is OK for the installation ( **bibcure-0.2.5.tar.gz**). I am using OSX Sierra (10.12.6).

However, when I type 'bibcure' in the terminal, I get: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 429, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'journalabbrev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bibcure", line 17, in <module>
    from bibcure.database import Db_abbrev
  File "/usr/local/lib/python3.6/site-packages/bibcure/database.py", line 18, in <module>
    "data/db_abbrev.json")
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1197, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'journalabbrev'
```

What did I do wrong? It seems that the module journalabbrev is missing, but this module does not seem to exist anymore.

Thanks!

**Comment by devmessias** [comment]
Man, I' so stupid. Why I changed the name of the package? [commit](https://github.com/bibcure/bibcure/commit/d8e98d5cb71371b32bb802c1573553c35a166cda)

I submitted a new version([0.2.6](https://github.com/bibcure/bibcure/releases/tag/0.2.6)) Please, could you install the new version and tell me if everything is ok?

```
pip uninstall bibcure
pip install bibcure --no-cache-dir
```

**Comment by jbmouret** [comment]
Thanks a lot! it works fine now.

**Comment by devmessias** [comment]
Thanks for reporting this issue  @jbmouret.
